# Generated by Django 3.2.19 on 2023-06-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('postal_code', models.CharField(max_length=20, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do Cliente')),
                ('value', models.FloatField(verbose_name='Valor da proposta de empréstimo')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('denied', 'Negado')], max_length=20, verbose_name='Status da Proposta')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.address', verbose_name='Endereço')),
            ],
        ),
    ]
