# Generated by Django 3.2.19 on 2023-06-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Proposta de Empréstimo'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.address', verbose_name='Endereço'),
        ),
    ]
