# Generated by Django 4.2.2 on 2023-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Endereço'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Aprovado'), ('denied', 'Negado'), ('pending', 'Pendente')], default='pending', max_length=20, null=True, verbose_name='Status da Proposta'),
        ),
    ]
